services:
  backend:
    container_name: example-nodejs-pm2
    image: example-nodejs-pm2:dev
    restart: always
    ports:
      - 3010:3000
    networks:
      local-network:
        ipv4_address: 172.20.10.25
networks:
  local-network:
    external: true
