services:
  example-php:
    container_name: example-php
    image: example-php:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # volumes:
    #   - ./sources:/usr/local/apache2/htdocs
    environment:
      - DATABASE_HOST=172.17.0.4
      - DATABASE_PORT=1521
      - DATABASE_SID=ORCLCDB
      - DATABASE_SERVICE_NAME=ORCLCDB
      - DATABASE_USER=OU_PHEA_PHP_PRJ
      - DATABASE_USER_PWD=7ZOxAHWXjB
    ports:
      - 8001:80
    networks:
      local-network:
        ipv4_address: 172.20.10.15
networks:
  local-network:
    external: true
